# Generated by Django 3.2.10 on 2022-02-19 03:51

import Apps.Chat.models
import Apps.Chat.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('code', models.CharField(default=Apps.Chat.models.random_code, max_length=100, unique=True, verbose_name='Room Code')),
                ('password', models.CharField(default='', max_length=100, null=True, verbose_name='Room Password')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='Room Description')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Room Closed')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Room Deleted')),
                ('need_permission', models.BooleanField(default=True, verbose_name='Need Creator Permission To Enter')),
                ('cover', models.ImageField(default='rooms/defaultCover.jpg', storage=Apps.Chat.storages.LocalStorage(), upload_to=Apps.Chat.models.user_directory_path, verbose_name='Room Cover Image')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Room Last Updated Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Room Creation Date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1000, verbose_name='Room Message')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is User Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Message Creation Date')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_Room', to='Chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_From_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Room Admin')),
                ('is_pending', models.BooleanField(default=True, verbose_name='Is Pending User')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is User Deleted')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Member Last Updated Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Member Creation Date')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
