# Generated by Django 3.2.10 on 2022-02-22 02:51

import Apps.Chat.models
import Apps.Chat.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cover',
            field=models.ImageField(default='rooms/defaultCover.jpg', storage=Apps.Chat.storages.default_storage, upload_to=Apps.Chat.models.user_directory_path, verbose_name='Room Cover Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Room Password'),
            preserve_default=False,
        ),
    ]
